name: deploy my web

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'cloudlyncsdevopslabs'   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'myweb.zip'      # set this to the path to your web app project, defaults to the repository root



jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4



    - name: Build-Artifacts-Zip Package
      run: |
        pwd
        zip -r myweb.zip *  #zip all html files


    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_MYSITE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
